### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jeroenmaes** [JonckheereM/Public#5]
Sommige links linken nog naar '#'

**Comment by JonckheereM** [comment]
Dat is inderdaad zo bij pubDetail en drinkDetail. Zo is het probleem met de linken (kon enkel op naam klikken) opgelost en zo komt er ook een back button vanboven waar zonder redirect terug naar de vorige pagina kan gegaan worden (zo moet niet iedere keer die pubs en drinks opgehaald worden.

**Comment by jeroenmaes** [comment]
Super!

Op de niet mobile site ook nog af en toe zo een '#' link te bespeuren.

**Comment by JonckheereM** [comment]
ok
